#!/usr/bin/env ruby

require './boot'

if ARGV[0] == '-v' || ARGV[0] == '--verbose'
  puts ">> Starting Rails lightweight stack"
  Rails.configuration.middleware.each do |middleware|
    puts "use #{middleware.inspect}"
  end
  puts "run #{Rails.application.class.name}.routes"
end


options = {
  :environment => nil,
  :pid         => nil,
  :Port        => 3000,
  :Host        => "0.0.0.0",
  :AccessLog   => [],
  :app         => TinyRailsApp,

  # TODO:
  # :server      => 'thin'
}

Rack::Server.start options
