source :rubygems

# Required by active_support
gem "tzinfo"

gem "actionpack",   "~> 3.2"
gem "activemodel",  "~> 3.2"
gem "activerecord", "~> 3.2"
gem "railties",     "~> 3.2"

gem 'sqlite3'

gem 'jquery-rails'
gem 'haml-rails'
gem 'sass-rails'
gem 'coffee-rails'
